[package]
name = "alicesaidhi/class-switcher"
version = "0.1.0"
private = true
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
videkit = "alicesaidhi/videkit-ty@0.1.1"
vide = "aloroid/vide-with-types@0.2.3"